pragma Singleton
import Quickshell

Singleton {
    property string bell: "\ue059"
    property string volumeFull: "\ue1ab"
    property string volumeLow: "\ue1aa"
    property string volumeOff: "\ue626"
    property string volumeMute: "\ue1ac"
    property string play: "\ue13c"
    property string pause: "\ue12e"
    property string previous: "\ue147"
    property string next: "\ue0bd"
    property string lyrics: "\ue349"
    property string lyricsBack: "\ue4de"
    property string youtubeDownload: "\ue5ec"
    property string check: "\ue226"
    property string cog: "\ue154"
    property string more: "\ue0b6"
    property string brightnessFull: "\ue178"
    property string brightnessMed: "\ue2b1"
    property string brightnessLow: "\ue299"
    property string bellOff: "\ue05a"
    property string bellRing: "\ue059"
    property string nightLight: "\ue2b2"
    property string recording: "\ue3f6"
    property string bellCheck: "\ue6ef"
    property string image: "\ue0f6"
    property string video: "\ue481"
    property string folder: "\ue0d7"
    property string convert: "\ue144"
    property string scanText: "\ue538"
    property string phone: "\ue133"
    property string mic: "\ue118"
    property string micOff: "\ue119"
    property string deafen: "\ue0f1"
    property string deafenOff: "\ue629"
    property string camera: "\ue1a5"
    property string cameraOff: "\ue1a6"
    property string screenshare: "\ue14f"
    property string screenshareOff: "\ue150"
    property string music: "\ue122"
    property string search: "\ue151"
    property string computer: "\ue77c"
    property string home: "\ue0f5"
    property string desktop: "\ue11d"
    property string documents: "\ue0cc"
    property string downloads: "\ue318"
    property string pictures: "\ue31c"
    property string videos: "\ue321"
    property string recent: "\ue087"
    property string devices: "\ue0ed"
    property string arrowLeft: "\ue048"
    property string arrowRight: "\ue049"
    property string warehouse: "\ue3e6"
}
   