pragma Singleton
import Quickshell

Singleton {
    property string bell: "\ue059"
    property string volumeFull: "\ue1ab"
    property string volumeLow: "\ue1aa"
    property string volumeOff: "\ue626"
    property string volumeMute: "\ue1ac"
    property string play: "\ue13c"
    property string pause: "\ue12e"
    property string previous: "\ue147"
    property string next: "\ue0bd"
    property string lyrics: "\ue349"
    property string lyricsBack: "\ue4de"
    property string youtubeDownload: "\ue5ec"
    property string check: "\ue226"
    property string cog: "\ue154"
    property string more: "\ue0b6"
    property string brightnessFull: "\ue178"
    property string brightnessMed: "\ue2b1"
    property string brightnessLow: "\ue299"
    property string bellOff: "\ue05a"
    property string bellRing: "\ue059"
    property string nightLight: "\ue2b2"
    property string recording: "\ue3f6"
    property string bellCheck: "\ue6ef"
    property string image: "\ue0f6"
    property string video: "\ue481"
    property string folder: "\ue0d7"
    property string convert: "\ue144"
    property string scanText: "\ue538"
}   